
global:
  log-level: debug
drivers:
  - name: d2
    type: s7
    tags:
      - name: tag1
        address: DB1.DBD0
        type: float32
  - name: d3
    type: opcua
    tags:
      - name: tag2
        address: ns=2;s=Tag2
        type: int32
transports:
  - name: t1
    type: mqtt
rules:
  - name: r2
    match: ALL
    action: forward
    target: t1
